### Read Datasets(csv,json,parquet)

In [25]:
import pandas as pd

In [26]:
import numpy as np

In [27]:
import os

## CSV File

In [28]:
csv_path="C:\\Users\\dhara\\Downloads\\customers-10000.csv"

### Read  dataset

In [29]:
df_csv1=pd.read_csv(csv_path)

In [30]:
df_csv1

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,DD0caa06ebf217c,Meghan,Cline,Richardson LLC,Petersport,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,2022-04-27,http://thomas-ramos.com/
9996,9997,C1C62ff90D0AfED,Jeremiah,Pena,Hodge-Nixon,Briggsport,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,2022-01-17,https://www.campbell.com/
9997,9998,2EfAa6Fe435A7DA,Peggy,Key,Vang LLC,West Joyceport,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,2022-01-13,http://www.george-scott.com/
9998,9999,5dB06C3Fab5CCCb,Evan,Humphrey,Gould Ltd,Camachochester,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,2020-04-14,https://www.payne.info/
9999,10000,9903e8fF4D8Ff0F,Melissa,Montgomery,Burns-Holden,Sparkstown,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,2020-06-27,http://nixon.net/

In [31]:
csv_path2="C:\\Users\\dhara\\Downloads\\city.csv.csv"

In [32]:
csv_path3="C:\\Users\\dhara\\Downloads\\csv\\email.csv"

In [33]:
df_csv2=pd.read_csv(csv_path)

In [34]:
df_csv3=pd.read_csv(csv_path)

In [35]:
df_csv2

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,DD0caa06ebf217c,Meghan,Cline,Richardson LLC,Petersport,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,2022-04-27,http://thomas-ramos.com/
9996,9997,C1C62ff90D0AfED,Jeremiah,Pena,Hodge-Nixon,Briggsport,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,2022-01-17,https://www.campbell.com/
9997,9998,2EfAa6Fe435A7DA,Peggy,Key,Vang LLC,West Joyceport,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,2022-01-13,http://www.george-scott.com/
9998,9999,5dB06C3Fab5CCCb,Evan,Humphrey,Gould Ltd,Camachochester,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,2020-04-14,https://www.payne.info/
9999,10000,9903e8fF4D8Ff0F,Melissa,Montgomery,Burns-Holden,Sparkstown,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,2020-06-27,http://nixon.net/

In [36]:
df_csv2

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,DD0caa06ebf217c,Meghan,Cline,Richardson LLC,Petersport,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,2022-04-27,http://thomas-ramos.com/
9996,9997,C1C62ff90D0AfED,Jeremiah,Pena,Hodge-Nixon,Briggsport,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,2022-01-17,https://www.campbell.com/
9997,9998,2EfAa6Fe435A7DA,Peggy,Key,Vang LLC,West Joyceport,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,2022-01-13,http://www.george-scott.com/
9998,9999,5dB06C3Fab5CCCb,Evan,Humphrey,Gould Ltd,Camachochester,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,2020-04-14,https://www.payne.info/
9999,10000,9903e8fF4D8Ff0F,Melissa,Montgomery,Burns-Holden,Sparkstown,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,2020-06-27,http://nixon.net/

In [37]:
df_csv1.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/

In [38]:
df_csv2.tail()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
9995,9996,DD0caa06ebf217c,Meghan,Cline,Richardson LLC,Petersport,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,2022-04-27,http://thomas-ramos.com/
9996,9997,C1C62ff90D0AfED,Jeremiah,Pena,Hodge-Nixon,Briggsport,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,2022-01-17,https://www.campbell.com/
9997,9998,2EfAa6Fe435A7DA,Peggy,Key,Vang LLC,West Joyceport,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,2022-01-13,http://www.george-scott.com/
9998,9999,5dB06C3Fab5CCCb,Evan,Humphrey,Gould Ltd,Camachochester,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,2020-04-14,https://www.payne.info/
9999,10000,9903e8fF4D8Ff0F,Melissa,Montgomery,Burns-Holden,Sparkstown,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,2020-06-27,http://nixon.net/

### JSON File

In [59]:
import json

In [60]:
import os

In [61]:
import pandas as pd

In [62]:
json_path1="C:\\Users\\dhara\\Documents\\dharani\\500.json"

In [65]:
with open(json_path1,"r")as file:
    data1=json.load(file)

In [66]:
df_json1=pd.json_normalize(raw_data1)

In [67]:
df_json1

,id,firstName,lastName,email,username,phone
0,11f39ca8-0ae3-4ed7-bda5-09401ae3ddd0,Bethany,Prohaska,Bertha45@yahoo.com,Nicholaus_Schroeder12,678.898.8618 x1599
1,7a2886cc-ccd1-4609-b9fd-72b7694a58e2,Cydney,Jacobi,Amanda91@hotmail.com,Ned36,(571) 343-4863 x461
2,fa1e2c1c-5760-4bd3-ac99-66772c0b5384,Raul,Stoltenberg,Tierra.Friesen18@hotmail.com,Leanne.Abshire13,1-993-432-4283
3,7b637405-afab-4ca4-8d59-f257d4e44f7b,Rita,Kling,Morgan.Brown@yahoo.com,Matt.Hammes,1-925-583-9516 x91812
4,7e944f03-a1c4-4eff-b167-b5aa20848282,Madge,Yundt,Shakira.Moen93@gmail.com,Isai_Abshire91,596-467-4510 x25659
...,...,...,...,...,...,...
495,3ac787c7-c12a-4cfc-b1c8-0280002b5b42,Carter,Will,Madison70@hotmail.com,Leann_Miller-Murazik28,953-414-9709 x6253
496,062ebb1c-c508-45b6-a2d2-6b9a42b1b1ba,Johnathon,Little,Brendon76@yahoo.com,Margret16,(658) 842-1640 x0989
497,5cff333b-73d2-4042-a122-fae410e94252,Millie,Bradtke,Jevon_Bode64@yahoo.com,Helena42,(510) 233-8223 x085
498,8b71efb5-e8e7-4703-957a-313706f44f37,Elliott,Greenfelder,Haylee89@gmail.com,Hollie_Cummerata46,707.369.1521 x3828
499,2f4da3a5-e04d-4f84-8c4c-8d2f2e02514c,Natalia,Crist,Ryleigh58@hotmail.com,Keanu.Effertz27,937-324-0743 x9345

In [68]:
df_json1.head()

,id,firstName,lastName,email,username,phone
0,11f39ca8-0ae3-4ed7-bda5-09401ae3ddd0,Bethany,Prohaska,Bertha45@yahoo.com,Nicholaus_Schroeder12,678.898.8618 x1599
1,7a2886cc-ccd1-4609-b9fd-72b7694a58e2,Cydney,Jacobi,Amanda91@hotmail.com,Ned36,(571) 343-4863 x461
2,fa1e2c1c-5760-4bd3-ac99-66772c0b5384,Raul,Stoltenberg,Tierra.Friesen18@hotmail.com,Leanne.Abshire13,1-993-432-4283
3,7b637405-afab-4ca4-8d59-f257d4e44f7b,Rita,Kling,Morgan.Brown@yahoo.com,Matt.Hammes,1-925-583-9516 x91812
4,7e944f03-a1c4-4eff-b167-b5aa20848282,Madge,Yundt,Shakira.Moen93@gmail.com,Isai_Abshire91,596-467-4510 x25659

In [69]:
df_json1.tail()

,id,firstName,lastName,email,username,phone
495,3ac787c7-c12a-4cfc-b1c8-0280002b5b42,Carter,Will,Madison70@hotmail.com,Leann_Miller-Murazik28,953-414-9709 x6253
496,062ebb1c-c508-45b6-a2d2-6b9a42b1b1ba,Johnathon,Little,Brendon76@yahoo.com,Margret16,(658) 842-1640 x0989
497,5cff333b-73d2-4042-a122-fae410e94252,Millie,Bradtke,Jevon_Bode64@yahoo.com,Helena42,(510) 233-8223 x085
498,8b71efb5-e8e7-4703-957a-313706f44f37,Elliott,Greenfelder,Haylee89@gmail.com,Hollie_Cummerata46,707.369.1521 x3828
499,2f4da3a5-e04d-4f84-8c4c-8d2f2e02514c,Natalia,Crist,Ryleigh58@hotmail.com,Keanu.Effertz27,937-324-0743 x9345

In [76]:
print("Total JSOM Records:",len(data1))

Total JSOM Records: 500

In [78]:
print("\nFlattend JSON columns:")
print(df_json1.columns)

Flattend JSON columns:
Index(['id', 'firstName', 'lastName', 'email', 'username', 'phone'], dtype='str')

### Parquet file

In [1]:
pip install pyarrow

Collecting pyarrow
  Using cached pyarrow-23.0.1-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
Downloading pyarrow-23.0.1-cp312-cp312-win_amd64.whl (27.6 MB)
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--

In [3]:
import pandas as pd

In [7]:
parquet_path="C:\\Users\\dhara\\Documents\\dharani\\weather.parquet"

In [8]:
df_parquet=pd.read_parquet(parquet_path,engine="pyarrow")

In [9]:
df_parquet

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30,SW,NW,6,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39,E,W,4,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85,N,NNE,6,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54,WNW,W,30,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50,SSE,ESE,20,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76,SSE,NW,7,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48,NNW,NNW,2,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43,ENE,ENE,11,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46,SSW,WNW,6,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78,NW,WNW,31,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [10]:
print("\nSample Records:")
print(df_parquet.head())

Sample Records:
   MinTemp  MaxTemp  Rainfall  Evaporation Sunshine WindGustDir WindGustSpeed  \
0      8.0     24.3       0.0          3.4      6.3          NW            30
1     14.0     26.9       3.6          4.4      9.7         ENE            39
2     13.7     23.4       3.6          5.8      3.3          NW            85
3     13.3     15.5      39.8          7.2      9.1          NW            54
4      7.6     16.1       2.8          5.6     10.6         SSE            50

  WindDir9am WindDir3pm WindSpeed9am  ...  Humidity3pm  Pressure9am  \
0         SW         NW            6  ...           29       1019.7
1          E          W            4  ...           36       1012.4
2          N        NNE            6  ...           69       1009.5
3        WNW          W           30  ...           56       1005.5
4        SSE        ESE           20  ...           49       1018.3

   Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
0       1015.0         7         7     14.4     23.6         No      3.6
1       1008.4         5         3     17.5     25.7        Yes      3.6
2       1007.2         8         7     15.4     20.2        Yes     39.8
3       1007.0         2         7     13.5     14.1        Yes      2.8
4       1018.5         7         7     11.1     15.4        Yes      0.0

  RainTomorrow
0          Yes
1          Yes
2          Yes
3          Yes
4           No

[5 rows x 22 columns]

In [11]:
print("\nSample Records:")
print(df_parquet.tail())

Sample Records:
     MinTemp  MaxTemp  Rainfall  Evaporation Sunshine WindGustDir  \
361      9.0     30.7       0.0          7.6     12.1         NNW
362      7.1     28.4       0.0         11.6     12.7           N
363     12.5     19.9       0.0          8.4      5.3         ESE
364     12.5     26.9       0.0          5.0      7.1          NW
365     12.3     30.2       0.0          6.0     12.6          NW

    WindGustSpeed WindDir9am WindDir3pm WindSpeed9am  ...  Humidity3pm  \
361            76        SSE         NW            7  ...           15
362            48        NNW        NNW            2  ...           22
363            43        ENE        ENE           11  ...           47
364            46        SSW        WNW            6  ...           39
365            78         NW        WNW           31  ...           13

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
361       1016.1       1010.8         1         3     20.4     30.0
362       1020.0       1016.9         0         1     17.2     28.2
363       1024.0       1022.8         3         2     14.5     18.3
364       1021.0       1016.2         6         7     15.8     25.9
365       1009.6       1009.2         1         1     23.8     28.6

     RainToday  RISK_MM RainTomorrow
361         No      0.0           No
362         No      0.0           No
363         No      0.0           No
364         No      0.0           No
365         No      0.0           No

[5 rows x 22 columns]

In [12]:
print("\nparquet Data Types:")
print(df_parquet.dtypes)

parquet Data Types:
MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine             str
WindGustDir          str
WindGustSpeed        str
WindDir9am           str
WindDir3pm           str
WindSpeed9am         str
WindSpeed3pm       int64
Humidity9am        int64
Humidity3pm        int64
Pressure9am      float64
Pressure3pm      float64
Cloud9am           int64
Cloud3pm           int64
Temp9am          float64
Temp3pm          float64
RainToday            str
RISK_MM          float64
RainTomorrow         str
dtype: object